version: '3'
services:
  book:
    image: emdupre/jupyter-book
    ports:
       - '4000:4000'
    volumes:
       - '.:/srv/jekyll'
    user: 1000:1000
    security_opt:
       - label:disable
    command: /bin/bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload"
    tty: true
